WARNING 2020-05-28 15:36:01,710 log 16700 14080 Method Not Allowed (POST): /search/find-by/name
WARNING 2020-05-28 15:36:28,242 log 15376 8296 Not Found: /search/find-by/name
WARNING 2020-05-28 15:39:11,781 log 8236 15108 Not Found: /search/find-by/name
WARNING 2020-05-28 15:40:11,241 log 12908 4940 Not Found: /search/find-by/name
WARNING 2020-05-28 15:40:11,242 log 12908 4940 Not Found: /search/find-by/name
WARNING 2020-05-28 15:42:31,501 log 7492 12112 Not Found: /search/find-by/name
WARNING 2020-05-28 15:44:21,580 log 15308 9420 Not Found: /search/find-by/name
WARNING 2020-05-28 15:48:40,850 log 8856 7600 Not Found: /search/find-by/name
WARNING 2020-05-28 15:49:06,897 log 15668 15680 Not Found: /search/find-by/name
ERROR 2020-05-28 15:53:51,053 log 5076 2252 Internal Server Error: /search/find-by/name
Traceback (most recent call last):
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\Twitter\views\search.py", line 60, in find_users_by_name
    if form.cleaned_data['content'] is not '':
AttributeError: 'SearchForm' object has no attribute 'cleaned_data'
ERROR 2020-05-28 15:54:08,417 log 12508 7260 Internal Server Error: /search/find-by/name
Traceback (most recent call last):
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\Twitter\views\search.py", line 60, in find_users_by_name
    if form.cleaned_data['content'] is not '':
AttributeError: 'SearchForm' object has no attribute 'cleaned_data'
ERROR 2020-05-28 15:54:40,242 log 16200 9484 Internal Server Error: /search/find-by/name
Traceback (most recent call last):
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\Twitter\views\search.py", line 60, in find_users_by_name
    if form.cleaned_data['content'] is not ' ':
AttributeError: 'SearchForm' object has no attribute 'cleaned_data'
ERROR 2020-05-28 15:55:25,204 log 18004 14432 Internal Server Error: /search/find-by/name
Traceback (most recent call last):
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\Twitter\views\search.py", line 60, in find_users_by_name
    if form.cleaned_data['content'] is not '':
AttributeError: 'SearchForm' object has no attribute 'cleaned_data'
WARNING 2020-05-28 15:55:58,048 log 8236 16188 Not Found: /search/find-by/name
WARNING 2020-05-28 15:57:36,642 log 12320 8332 Not Found: /search/find-by/name
WARNING 2020-05-28 15:57:36,654 log 12320 8332 Not Found: /search/find-by/username
WARNING 2020-05-28 16:00:35,731 log 9296 10708 Not Found: /search/find-by/name
WARNING 2020-05-28 16:00:35,743 log 9296 10708 Not Found: /search/find-by/username
WARNING 2020-05-28 16:00:35,755 log 9296 10708 Method Not Allowed (GET): /like/123/
WARNING 2020-05-28 16:00:50,953 log 16932 2332 Not Found: /search/find-by/name
WARNING 2020-05-28 16:00:50,965 log 16932 2332 Not Found: /search/find-by/username
WARNING 2020-05-28 16:54:04,483 log 16712 16548 Not Found: /search/find-by/name
WARNING 2020-05-28 16:54:36,168 log 15220 15524 Not Found: /search/find-by/name
WARNING 2020-05-28 16:54:36,180 log 15220 15524 Not Found: /search/find-by/username
WARNING 2020-05-28 16:59:50,499 log 14828 2740 Method Not Allowed (PATCH): /twit/create/
WARNING 2020-05-28 17:10:27,421 log 92 9408 Not Found: /search/find-by/username
WARNING 2020-05-28 17:34:51,329 log 14876 17508 Bad Request: /twit/create/
WARNING 2020-05-28 21:50:30,502 log 4848 7660 Bad Request: /twit/create/
WARNING 2020-05-28 21:50:31,256 log 4848 7660 Not Found: /search/find-by/name
WARNING 2020-05-28 21:50:31,277 log 4848 7660 Not Found: /search/find-by/username
ERROR 2020-05-28 22:06:03,114 log 13280 11452 Internal Server Error: /like/1/
Traceback (most recent call last):
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\DEV\LAB_3_Twitter\Twitter\Twitter\views\feedback.py", line 13, in like_view
    body = json.loads(request.body)
  File "C:\Users\WyTra\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\WyTra\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\WyTra\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING 2020-05-28 22:10:28,468 log 17976 15232 Not Found: /search/find-by/name
WARNING 2020-05-28 22:22:56,924 log 19096 2764 Bad Request: /twit/create/
WARNING 2020-05-28 22:22:59,324 log 19096 2764 Not Found: /search/find-by/name
WARNING 2020-05-28 22:22:59,343 log 19096 2764 Not Found: /search/find-by/username
WARNING 2020-05-28 22:35:17,095 log 9708 12508 Bad Request: /twit/create/
WARNING 2020-05-28 22:50:27,436 log 13920 19328 Method Not Allowed (PATCH): /bookmarks/
WARNING 2020-05-28 22:53:00,378 log 10932 15996 Method Not Allowed (GET): /bookmarks/add/1
WARNING 2020-05-28 23:09:50,795 log 3604 12192 Method Not Allowed (DELETE): /bookmarks/remove/0
WARNING 2020-05-28 23:14:33,615 log 14472 10508 Bad Request: /twit/create/
WARNING 2020-05-28 23:14:35,966 log 14472 10508 Not Found: /search/find-by/name
WARNING 2020-05-28 23:14:35,985 log 14472 10508 Not Found: /search/find-by/username
WARNING 2020-06-04 15:32:15,758 log 19688 17596 Bad Request: /twit/create/
WARNING 2020-06-04 15:32:16,469 log 19688 17596 Not Found: /search/find-by/name
WARNING 2020-06-04 15:32:16,488 log 19688 17596 Not Found: /search/find-by/username
WARNING 2020-06-04 15:40:34,620 log 1484 20808 Bad Request: /twit/create/
WARNING 2020-06-04 15:42:05,041 log 18268 12608 Bad Request: /twit/create/
WARNING 2020-06-04 15:42:05,708 log 18268 12608 Not Found: /search/find-by/name
WARNING 2020-06-04 15:42:05,726 log 18268 12608 Not Found: /search/find-by/username
